### ISSUE TITLE
Wiki is gone, No idea how this works

### ISSUE THREAD

**Issue by talamaska** [timsneath/slideplayer#1]
Hi, I would like to try out and make this app working in Windows.
Unfortunately, the wiki is gone, so I don't have any idea of the slide file format.
Basically none of the links pointing to the wiki are not working.
I would love to use this app to present flutter in the company I work for.

**Comment by timsneath** [comment]
Hi there! Yeah, I'm sorry -- this is unsupported and probably broken code at this point. There's an example presentation here: https://github.com/timsneath/slideplayer/blob/main/example_presentation/flutter_live.json but it's not trivial. A lot of this was handcrafted code for a one off event.
